# Generated by Django 5.2.8 on 2026-08-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0002_alter_lake_options'),
        ('quiz', '0002_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lakes.lake'),
        ),
    ]
