# Generated by Django 5.2.8 on 2026-04-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lake',
            options={'ordering': ['id']},
        ),
    ]
